
#pragma once
// NOTE: macro dependency can't be too long to overflow the stack






#define TIMER_FILE_CREATE 0
#define TIMER_FILE_OPEN (TIMER_FILE_CREATE + 1)
#define TIMER_FILE_GET (TIMER_FILE_OPEN + 1)
#define TIMER_FILE_SPECIFIC (TIMER_FILE_GET + 1)
#define TIMER_FILE_OPTIONAL (TIMER_FILE_SPECIFIC + 1)
#define TIMER_FILE_CLOSE (TIMER_FILE_OPTIONAL + 1)
#define TIMER_GROUP_CREATE 9
#define TIMER_GROUP_OPEN (TIMER_GROUP_CREATE + 1)
#define TIMER_GROUP_GET (TIMER_GROUP_OPEN + 1)
#define TIMER_GROUP_SPECIFIC (TIMER_GROUP_GET + 1)
#define TIMER_GROUP_OPTIONAL (TIMER_GROUP_SPECIFIC + 1)
#define TIMER_GROUP_CLOSE (TIMER_GROUP_OPTIONAL + 1)
#define TIMER_ATT_CREATE 15
#define TIMER_ATT_OPEN (TIMER_ATT_CREATE + 1)
#define TIMER_ATT_READ (TIMER_ATT_OPEN + 1)
#define TIMER_ATT_WRITE (TIMER_ATT_READ + 1)
#define TIMER_ATT_GET (TIMER_ATT_WRITE + 1)
#define TIMER_ATT_SPECIFIC (TIMER_ATT_GET + 1)
#define TIMER_ATT_OPTIONAL (TIMER_ATT_SPECIFIC + 1)
#define TIMER_ATT_CLOSE (TIMER_ATT_OPTIONAL + 1)
#define TIMER_DATASET_CREATE 23
#define TIMER_DATASET_OPEN (TIMER_DATASET_CREATE + 1)
#define TIMER_DATASET_READ (TIMER_DATASET_OPEN + 1)
#define TIMER_DATASET_WRITE (TIMER_DATASET_READ + 1)
#define TIMER_DATASET_GET (TIMER_DATASET_WRITE + 1)
#define TIMER_DATASET_SPECIFIC (TIMER_DATASET_GET + 1)
#define TIMER_DATASET_OPTIONAL (TIMER_DATASET_SPECIFIC + 1)
#define TIMER_DATASET_CLOSE (TIMER_DATASET_OPTIONAL + 1)
#define TIMER_H5VL_FILE_CREATE 28
#define TIMER_H5VL_FILE_OPEN (TIMER_H5VL_FILE_CREATE + 1)
#define TIMER_H5VL_FILE_GET (TIMER_H5VL_FILE_OPEN + 1)
#define TIMER_H5VL_FILE_SPECIFIC (TIMER_H5VL_FILE_GET + 1)
#define TIMER_H5VL_FILE_OPTIONAL (TIMER_H5VL_FILE_SPECIFIC + 1)
#define TIMER_H5VL_FILE_CLOSE (TIMER_H5VL_FILE_OPTIONAL + 1)
#define TIMER_H5VL_GROUP_CREATE 34
#define TIMER_H5VL_GROUP_OPEN (TIMER_H5VL_GROUP_CREATE + 1)
#define TIMER_H5VL_GROUP_GET (TIMER_H5VL_GROUP_OPEN + 1)
#define TIMER_H5VL_GROUP_SPECIFIC (TIMER_H5VL_GROUP_GET + 1)
#define TIMER_H5VL_GROUP_OPTIONAL (TIMER_H5VL_GROUP_SPECIFIC + 1)
#define TIMER_H5VL_GROUP_CLOSE (TIMER_H5VL_GROUP_OPTIONAL + 1)
#define TIMER_H5VL_ATT_CREATE 40
#define TIMER_H5VL_ATT_OPEN (TIMER_H5VL_ATT_CREATE + 1)
#define TIMER_H5VL_ATT_READ (TIMER_H5VL_ATT_OPEN + 1)
#define TIMER_H5VL_ATT_WRITE (TIMER_H5VL_ATT_READ + 1)
#define TIMER_H5VL_ATT_GET (TIMER_H5VL_ATT_WRITE + 1)
#define TIMER_H5VL_ATT_SPECIFIC (TIMER_H5VL_ATT_GET + 1)
#define TIMER_H5VL_ATT_OPTIONAL (TIMER_H5VL_ATT_SPECIFIC + 1)
#define TIMER_H5VL_ATT_CLOSE (TIMER_H5VL_ATT_OPTIONAL + 1)
#define TIMER_H5VL_DATASET_CREATE 48
#define TIMER_H5VL_DATASET_OPEN (TIMER_H5VL_DATASET_CREATE + 1)
#define TIMER_H5VL_DATASET_READ (TIMER_H5VL_DATASET_OPEN + 1)
#define TIMER_H5VL_DATASET_WRITE (TIMER_H5VL_DATASET_READ + 1)
#define TIMER_H5VL_DATASET_GET (TIMER_H5VL_DATASET_WRITE + 1)
#define TIMER_H5VL_DATASET_SPECIFIC (TIMER_H5VL_DATASET_GET + 1)
#define TIMER_H5VL_DATASET_OPTIONAL (TIMER_H5VL_DATASET_SPECIFIC + 1)
#define TIMER_H5VL_DATASET_CLOSE (TIMER_H5VL_DATASET_OPTIONAL + 1)
#define TIMER_FILEI_FLUSH 56
#define TIMER_FILEI_METAFLUSH (TIMER_FILEI_FLUSH + 1)
#define TIMER_FILEI_METAUPDATE (TIMER_FILEI_METAFLUSH + 1)
#define TIMER_DATASETI_GEN_RTYPE 59
#define TIMER_DATASETI_OPEN_UO (TIMER_DATASETI_GEN_RTYPE + 1)
#define TIMER_DATASPACEI_GET_SEL_TYPE 61
#define TIMER_DATASPACEI_GET_SEL (TIMER_DATASPACEI_GET_SEL_TYPE + 1)
#define TIMER_NB_FLUSH_READ_REQ 63
#define TIMER_NB_FLUSH_WRITE_REQ (TIMER_NB_FLUSH_READ_REQ + 1)

#define NTIMER (TIMER_NB_FLUSH_WRITE_REQ + 1)