
#pragma once
// NOTE: macro dependency can't be too long to overflow the stack






#define TIMER_FILE_CREATE 0
#define TIMER_FILE_OPEN (TIMER_FILE_CREATE + 1)
#define TIMER_FILE_GET (TIMER_FILE_OPEN + 1)
#define TIMER_FILE_SPECIFIC (TIMER_FILE_GET + 1)
#define TIMER_FILE_OPTIONAL (TIMER_FILE_SPECIFIC + 1)
#define TIMER_FILE_CLOSE (TIMER_FILE_OPTIONAL + 1)
#define TIMER_GROUP_CREATE 6
#define TIMER_GROUP_OPEN (TIMER_GROUP_CREATE + 1)
#define TIMER_GROUP_GET (TIMER_GROUP_OPEN + 1)
#define TIMER_GROUP_SPECIFIC (TIMER_GROUP_GET + 1)
#define TIMER_GROUP_OPTIONAL (TIMER_GROUP_SPECIFIC + 1)
#define TIMER_GROUP_CLOSE (TIMER_GROUP_OPTIONAL + 1)
#define TIMER_DATASET_CREATE 12
#define TIMER_DATASET_OPEN (TIMER_DATASET_CREATE + 1)
#define TIMER_DATASET_READ (TIMER_DATASET_OPEN + 1)
#define TIMER_DATASET_WRITE (TIMER_DATASET_READ + 1)
#define TIMER_DATASET_GET (TIMER_DATASET_WRITE + 1)
#define TIMER_DATASET_SPECIFIC (TIMER_DATASET_GET + 1)
#define TIMER_DATASET_OPTIONAL (TIMER_DATASET_SPECIFIC + 1)
#define TIMER_DATASET_CLOSE (TIMER_DATASET_OPTIONAL + 1)
#define TIMER_ATT_CREATE 20
#define TIMER_ATT_OPEN (TIMER_ATT_CREATE + 1)
#define TIMER_ATT_READ (TIMER_ATT_OPEN + 1)
#define TIMER_ATT_WRITE (TIMER_ATT_READ + 1)
#define TIMER_ATT_GET (TIMER_ATT_WRITE + 1)
#define TIMER_ATT_SPECIFIC (TIMER_ATT_GET + 1)
#define TIMER_ATT_OPTIONAL (TIMER_ATT_SPECIFIC + 1)
#define TIMER_ATT_CLOSE (TIMER_ATT_OPTIONAL + 1)

#define NTIMER (TIMER_ATT_CLOSE + 1)